import Banner from "@/pages/Banner/Banner";
import FooterPage from "@/pages/shared/Footer/Footer";
import UnderSubFooter from "@/pages/shared/Footer/UnderSubFooter";
import LeftSideRoute from "@/pages/shared/LeftSideRoute/LeftSideRoute";
import Navbar from "@/pages/shared/Navbar/Navbar";
import RightSideBox from "@/pages/shared/RightSideBox/RightSideBox";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inquiry",
  description: "Generated by Inquiry",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="bg-base-200 border-b border-slate-700">
            <div className="max-w-7xl mx-auto">
              <Navbar />
            </div>
          </div>
          <div className="h-72">
            <Banner/>
          </div>
          <div className="max-w-7xl mx-auto">
            <div className="grid grid-cols-10 justify-center items-center">
              <div className="col-span-2 border border-red-600 h-screen">
                <LeftSideRoute />
              </div>
              <div className="col-span-6">{children}</div>
              <div className="col-span-2 border border-red-600 h-screen">
                <RightSideBox />
              </div>
            </div>
          </div>
        </div>
        <div className="bg-base-200 border-t  border-slate-700">
          <div className="max-w-7xl mx-auto">
            <FooterPage />
          </div>
          <div className="bg-base-200 border-t  border-slate-800">
            <div className="max-w-7xl mx-auto">
              <UnderSubFooter />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
